// <auto-generated />
using System;
using Cpm.Api.Inftrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cpm.Api.Inftrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cpm.Api.Domain.Model.ClinicMasterModel", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IsApprove")
                        .HasColumnType("int");

                    b.Property<int>("IsPasswordChange")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ClinicId");

                    b.ToTable("Clinic_master");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.DoctorMasterModel", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("DoctorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorId");

                    b.HasIndex("SkillId");

                    b.ToTable("Doctor_master");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.LoginModel", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.HasIndex("RoleId");

                    b.ToTable("Login_Model");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.RoleMasterModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role_master");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.SkillMasterModel", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int?>("InsBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SkillId");

                    b.ToTable("Skill_master");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.DoctorMasterModel", b =>
                {
                    b.HasOne("Cpm.Api.Domain.Model.SkillMasterModel", "SkillMaster")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("SkillMaster");
                });

            modelBuilder.Entity("Cpm.Api.Domain.Model.LoginModel", b =>
                {
                    b.HasOne("Cpm.Api.Domain.Model.RoleMasterModel", "RoleMaster")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("RoleMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
